add integrations listing for user
fiberplane/fiberplane-archived pull request #142
Opened 2023-12-27 14:45 UTC by mellowagain

# Description

adds models for integration listing

fixes FP-3386

# Checklist

- [x] The changes have been tested to be backwards compatible.
- [x] The OpenAPI schema and generated client have been updated.
- [x] New models module has been added to api generator xtask
- [x] New types/fields are [well-documented and annotated](/CONTRIBUTING.md#adding-types-and-their-annotations).
- [ ] The CHANGELOG is updated.

> Please link any related PRs in other repositories that depend on this:

* Monofiber: https://github.com/fiberplane/monofiber/pull/193

After merging, please merge related PRs ASAP, so others don't get blocked.

2024-01-04 15:35 UTC, hatchan commented on fiberplane-models/src/integrations.rs
> +    AttentionRequired { reason: String }, // todo: check if this gets serialized correctly
I think I did ran into an issue _somewhere_ using this approach... Not sure what or where anymore, so not sure how useful this is haha.

2024-01-04 15:35 UTC, hatchan commented on fiberplane-models/src/integrations.rs
> +#[serde(rename_all = "camelCase")]
Shouldn't this be:

```suggestion
#[serde(rename_all = "snake_case", tag = "type")]
```

As that is what we're using in different places and we are including data.

2024-01-04 15:35 UTC, hatchan commented on schemas/openapi_v1.yml
> +            - "attentionRequired"
Don't think this will work with the serialization that we're using above (ie. with the embedded `reason`)

2024-01-08 09:29 UTC, arendjr commented on fiberplane-models/src/integrations.rs
> +    AttentionRequired { reason: String }, // todo: check if this gets serialized correctly
As long as you include the `tag = "type"` as @hatchan suggested in the previous comment, I think it should work.

2024-01-10 13:19 UTC, hatchan approved these changes

2024-01-10 13:24 UTC, stephlow requested changes

2024-01-10 13:24 UTC, stephlow commented on fiberplane-models/src/integrations.rs
> +    pub data: Option<serde_json::Value>,
```suggestion
    pub data: Option<Value>,
```

We need to import value at the top level otherwise fp-bindgen will generate this json:
```
    data?: serde_json::Value;
```

2024-01-10 15:14 UTC, mellowagain commented on fiberplane-models/src/integrations.rs
> +    pub data: Option<serde_json::Value>,
nice catch! but i yeeted `data` off the struct anyways so should be good now

2024-01-10 15:41 UTC, stephlow approved these changes

2024-01-11 14:12 UTC, hatchan approved these changes

2024-01-12 10:52 UTC, merged