Introduce webhooks
fiberplane/fiberplane-archived pull request #41
Opened 2023-03-27 15:11 UTC by mellowagain

# Description

Based on RFC-90 and RFC-91.

Fixes FP-3129
Fixes FP-3128

# Checklist

- [x] The changes have been tested to be backwards compatible.
- [x] The OpenAPI schema and generated client have been updated.
- [x] New models module has been added to API generator script.
- [x] New types/fields are [well-documented and annotated](/CONTRIBUTING.md#adding-types-and-their-annotations).
- [x] The CHANGELOG is updated.

> Please link any related PRs in other repositories that depend on this:

* API: https://github.com/fiberplane/api/pull/642
* FP: https://github.com/fiberplane/fp/pull/239

After merging, please merge related PRs ASAP, so others don't get blocked.

2023-04-11 07:05 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    pub endpoint: String,
These (types such as `String` and `Base64Uuid`, and `Timestamp` below) should use `#[builder(setter(into))]`.

2023-04-11 07:05 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    pub enabled: bool,
This can use `#[builder(default)]`.

2023-04-12 14:13 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    pub regenerate_shared_secret: Option<bool>,
It might make sense to omit the `Option` altogether here, because this is not a field being set on the webhook, but rather an instruction. It's a bit of a special case, I admit, but it might make the model slightly easier to use also.

```suggestion
    #[builder(default)]
    #[serde(default)]
    pub regenerate_shared_secret: bool,
```

2023-04-21 12:10 UTC, gagbo approved these changes

2023-04-24 06:02 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +#[serde(rename_all = "lowercase")]
We use `#[serde(rename_all = "snake_case")]` for enums. Could you add this to the `CONTRIBUTING.md` also?

2023-04-24 06:08 UTC, arendjr requested changes

2023-04-24 06:08 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +            value => panic!("unknown value {value}, expected 0 (ping) or 1 (frontmatter)"),
I think we should use `TryFrom` instead of panicking.

2023-04-24 06:08 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
A lot of `Option`s here that should use `#[builder(strip_option)]`.

2023-04-24 06:08 UTC, arendjr commented on schemas/openapi_v1.yml
> +        can re-deliver the ping payload and if that works, manually re-enable the webhook again.
Nice docs :+1:

2023-04-24 10:14 UTC, mellowagain commented on fiberplane-models/src/webhooks.rs
> +#[serde(rename_all = "lowercase")]
the categories for webhooks were spec'ed in the rfc to be completely lowercase, which is why I added this attribute. we can change it to `snake_case` tho, it'll only impact `frontmatter` which will become `front_matter`

2023-04-24 13:01 UTC, arendjr approved these changes
:partying_face:

2023-04-24 13:01 UTC, mellowagain commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
i actually remembered why after having done the change lol

turns out that i need the setters to accept a `Option` as these fields can be null in the database on the api side as well

2023-04-24 13:02 UTC, mellowagain commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
i added a comment explaining why

2023-04-24 13:10 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
Right. I see why you'd take that route, though personally I think we should just take the pain in the API so the models stay consistent. After all, it's not as if the API cannot use the type anymore, it just becomes less convenient *in that specific instance*. But by making exceptions based on usage in the API, we're effectively creating an inconsistent public API based on which usages are convenient in one of our internal projects.

We have a bunch of other places too that look similar to what we could do here:

```rs
let mut delivery = WebhookDelivery::builder()
    .id(delivery_id)
    .webhook_id(webhook_id)
    // more of these
    .build();
delivery.inconvenient_option = option_from_db;
delivery
```

2023-04-24 13:13 UTC, mellowagain commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
i mean fair, yea i guess it makes more sense to have a consistent and clean interface publicly than to have a bit of pain in the api privately, i'll revert the commit

2023-04-24 13:14 UTC, arendjr commented on fiberplane-models/src/webhooks.rs
> +    #[builder(default, setter(into))]
Thanks!

2023-05-02 09:42 UTC, hatchan requested changes

2023-05-02 09:42 UTC, hatchan commented on schemas/webhooks.schema.json
> +{
Where is this used?

2023-05-02 09:42 UTC, hatchan commented on fiberplane-models/src/webhooks.rs
> +use strum::IntoEnumIterator;
Little clippy that can be resolved

2023-05-02 09:42 UTC, hatchan commented on fiberplane-models/src/webhooks.rs
> +pub struct InvalidWebhookIdError(i16);
Shouldn't this be `InvalidWebhookCategoryError`?

2023-05-02 09:42 UTC, hatchan commented on fiberplane-models/src/webhooks.rs
> +    pub enabled: Option<bool>,
Maybe we can add some newlines in between the properties to make it a bit more readable.

```suggestion
    #[builder(default, setter(strip_option, into))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,

    #[builder(default, setter(strip_option))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<WebhookCategory>>,

    #[builder(default)]
    #[serde(default)]
    pub regenerate_shared_secret: bool,

    #[builder(default, setter(strip_option))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
```

Also applies to the other structs

2023-05-02 12:37 UTC, mellowagain commented on schemas/webhooks.schema.json
> +{
nowhere, it is simple here so others can use it

2023-05-02 12:37 UTC, mellowagain commented on fiberplane-models/src/webhooks.rs
> +use strum::IntoEnumIterator;
the import is in fact used by the expansion of the `EnumIter` proc macro

2023-05-02 13:31 UTC, hatchan approved these changes

2023-05-03 15:06 UTC, merged