Split charts lib
fiberplane/fiberplane-archived pull request #71
Opened 2023-07-05 12:38 UTC by arendjr

# Description

This extracts the "ACG" (abstract chart generator) to become a standalone component inside `fiberplane-charts`. Both the `MetricsChart` and the `SparkChart` call the ACG, while the internal `CoreChart` has been refactored to render abstract charts instead.

TODO:

- [ ] Make sure dragging along the X axis works
- [ ] Fix positioning of bar charts
- [ ] Fix percentage stacked charts

Implements [RFC 104](https://studio.fiberplane.com/workspaces/fiberplane/notebooks/RFC-104-Splitting-the-charts-library-5H6VTTRoTxmUpSxZERmNVg).

# Checklist

~~- [ ] The changes have been tested to be backwards compatible.~~
~~- [ ] The OpenAPI schema and generated client have been updated.~~
~~- [ ] New models module has been added to api generator xtask~~
- [ ] New types/fields are [well-documented and annotated](/CONTRIBUTING.md#adding-types-and-their-annotations).
- [ ] The CHANGELOG is updated.

> Please link any related PRs in other repositories that depend on this:

- [ ] Monofiber: https://github.com/fiberplane/monofiber/pull/TODO

After merging, please merge related PRs ASAP, so others don't get blocked.

2023-07-18 18:39 UTC, brettimus requested changes
did a quick first pass and found some non-blockers. will continue review tomorrow!

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/ChartShape/AreaShape.tsx
> +        // Keep this one around to spot any incorrect threshold computations.
Should we remove this in production builds?

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/ChartSizeContainerProvider.tsx
> +  const intersections = useIntersectionObserver(
aside: i appreciate all the little cleanup stuff you did

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/CoreChart.tsx
> +      style={{ cursor, marginTop: 2 }}
do you remember why `marginTop: 2` is here? if so, could you put a small comment for future readers?

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/CoreChart.tsx
> +      if (state.dragKeyPressed) {
nice semantic abstraction of the drag and zoom keypresses

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/GridWithAxes/BottomAxis.tsx
> +      {getTicks(xScale, numTicks).map((value, index) => (
something that the visx library did was add some extra space between the labels and axis. they had this as a default value of `8` on their AxisBottom component (see: [here](https://github.com/airbnb/visx/blob/94d561aa3f75e44b8d35918ea4da0cacd9177d98/packages/visx-axis/src/axis/AxisBottom.tsx#L17), which appears to be used to calculate a transform on the <text> elements [here](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/utils/getLabelTransform.ts#L14))

you can see the effect in this screenshot (refactored fiberplane-chars):

![image](https://github.com/fiberplane/fiberplane/assets/3201327/4809efd2-7f9c-4a7b-91be-1ab70ecc70db)

compared to this (old fiberplane-charts):

![image](https://github.com/fiberplane/fiberplane/assets/3201327/055f49f6-3245-4765-a400-2c565aab42b9)

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/GridWithAxes/GridWithAxes.tsx
> +    return motionValue.on("change", (value) => setCurrent(value));
nice, i think this will resolve a warning we were getting in the console

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/GridWithAxes/LeftAxis.tsx
> +  const tickLabelProps = {
same comment as with BottomAxis: it could be nice to add a `labelOffset` of some sort, to put some space between the labels and axis. could be simple for now, a fixed value

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/hooks/useMouseControls.ts
> +    const coords = getCoordinatesForEvent(event, dimensions);
this is throwing errors for me on wheel events. getCoordinatesForevent assumes that `event.target` is the svg element, and at least for me (latest chrome), it's usually the `window` object. so, when it tries to get the bounding client rect to calculate coordinates, we throw an error. 

the effect is that "scroll to zoom in or zoom out" doesn't work anymore. not a blocker imo, but worth following up on

2023-07-18 18:39 UTC, brettimus commented on fiberplane-charts/src/CoreChart/hooks/useMouseControls.ts
> +    const coords = getCoordinatesForEvent(event, dimensions);
the previous implementation relied on a ref to the chart content:

```ts
 const graphContent = graphContentRef.current;
    if (!graphContent) {
      return;
    }

    const rect = graphContent.getClientRects()[0];
    const x = event.pageX - (rect?.left ?? 0);
    if (x < 0 || x > xMax) {
      return;
    }
```

2023-07-19 06:57 UTC, arendjr commented on fiberplane-charts/src/CoreChart/ChartShape/AreaShape.tsx
> +        // Keep this one around to spot any incorrect threshold computations.
We kept it around thus far without trouble, I don't think it would make much difference...

It did actually help me debug an issue I had introduced though :)

2023-07-19 07:00 UTC, arendjr commented on fiberplane-charts/src/CoreChart/CoreChart.tsx
> +      style={{ cursor, marginTop: 2 }}
I have no idea... it was there, but also only for interactive charts and not read-only ones... I could not find a good reason for that either, so now it's always there. I assume it's just part of the design somehow...

2023-07-19 07:02 UTC, arendjr commented on fiberplane-charts/src/CoreChart/GridWithAxes/BottomAxis.tsx
> +      {getTicks(xScale, numTicks).map((value, index) => (
Good catch, thanks!

2023-07-19 07:19 UTC, arendjr commented on fiberplane-charts/src/CoreChart/GridWithAxes/GridWithAxes.tsx
> +    return motionValue.on("change", (value) => setCurrent(value));
Yeah, it does :)

2023-07-19 07:20 UTC, arendjr commented on fiberplane-charts/src/CoreChart/hooks/useMouseControls.ts
> +    const coords = getCoordinatesForEvent(event, dimensions);
Oh, great catch! I had fixed the scroll behavior, then moved the element to which the handler was attached to fix an issue where the default behavior could not be stopped, and forgot to check it afterwards.

2023-07-19 08:17 UTC, arendjr commented
I think I've addressed all the feedback thus far!

2023-07-19 10:30 UTC, brettimus commented on fiberplane-charts/src/Mondrian/generator/utils.ts
> +    getYAxisForConstantValue(minValue);
RFC 3339-formatted

2023-07-19 11:01 UTC, brettimus approved these changes
fantastic

2023-07-19 11:05 UTC, brettimus commented on fiberplane-charts/src/Mondrian/generator/utils.ts
> +    getYAxisForConstantValue(minValue);
i'm 99.99% sure this meant to have a return statement, so i just added it ✨

2023-07-19 11:33 UTC, arendjr commented on fiberplane-charts/src/Mondrian/generator/utils.ts
> +    getYAxisForConstantValue(minValue);
Perfect!

2023-07-19 12:08 UTC, merged