`fiberplane-charts`: Align ticks to buckets
fiberplane/fiberplane-archived pull request #75
Opened 2023-07-19 10:18 UTC by arendjr

# Description

This aligns ticks along the X axis to the buckets returned by Prometheus/the Provider. This makes for a much smoother experience with the tooltips especially.

Also reduces our dependency on VisX some more, since we don't use their `getTicks()` or grid components anymore.

# Checklist

- [ ] The changes have been tested to be backwards compatible.
- [ ] The OpenAPI schema and generated client have been updated.
- [ ] New models module has been added to api generator xtask
- [ ] New types/fields are [well-documented and annotated](/CONTRIBUTING.md#adding-types-and-their-annotations).
- [ ] The CHANGELOG is updated.

> Please link any related PRs in other repositories that depend on this:

After merging, please merge related PRs ASAP, so others don't get blocked.

2023-07-19 14:12 UTC, brettimus commented
small regression when "dragging" across time. in previous implementation, the grid lines (ticks) would move with the chart (see video)


https://github.com/fiberplane/fiberplane/assets/3201327/70b9fc52-9594-4bac-8fef-cf8b00656a7d

2023-07-19 14:35 UTC, brettimus commented
can't quite figure out what's causing this, but i just ran into a strange spacing issue:

<img width="1668" alt="image" src="https://github.com/fiberplane/fiberplane/assets/3201327/1aa0ed1f-0af6-4dad-8abb-c5329cb72147">

2023-07-19 14:51 UTC, arendjr commented
The spacing issue is the empty issue on the left, right? I suppose it can happen if you drag, but don't receive new data?

2023-07-19 15:07 UTC, brettimus commented
> 

ah no i think i can reproduce - happens when you look at a 12+ hour window i think (in explorer, it started getting funky after i switch to "Last 12 hours" and it remained funky for all other time ranges greater than that)

2023-07-19 15:14 UTC, brettimus commented
important context: i think it's because there isn't any data before 6 hours ago for the function i'm looking at. so, the absence of data leading up to when this function started to receive requests seems to be tripping up the gridlines

2023-07-19 15:29 UTC, brettimus requested changes
so it seems the tickSuggestions need to handle the case where we only have a small slice of data across a wide time range. that's my understanding of what's messing up the chart i posted. (the buckets used in suggestions for the x-axis ticks are calculated based off of the observed time values, but it's possible that the timeRange.from is significantly earlier than the min value from the datapoints in the data set, e.g.)



otherwise, i'd say getting the grid lines to move when you're in the "shift + grab" scenario is a non-blocker

2023-07-19 15:29 UTC, brettimus commented on fiberplane-charts/src/Mondrian/generator/utils/attachSuggestionsToXAxis.ts
> +  interval: number,
don't know if this would be overly defensive but should there be some sort of validation that `interval > 0` before the while loop?

2023-07-21 09:42 UTC, arendjr commented on fiberplane-charts/src/Mondrian/generator/utils/attachSuggestionsToXAxis.ts
> +  interval: number,
Not a bad idea.

2023-07-21 09:43 UTC, arendjr commented
Should be all good now.

2023-07-21 16:25 UTC, brettimus commented
so i'm still getting the spacing issue locally, when there are no data points at all on one end of the timeRange 

<img width="1060" alt="image" src="https://github.com/fiberplane/fiberplane/assets/3201327/5cc6766c-66be-484c-87a6-f7c38d125f6e">

this is easy to reproduce when you get something new started in explorer, and maybe you have a few minutes of actual data, but then your query asks for data in the past 15minutes. can pop up steps to repro if you want, or if you don't mind i can take a crack at it too?

2023-07-22 11:25 UTC, brettimus commented on fiberplane-charts/src/CoreChart/GridWithAxes/GridWithAxes.tsx
> +  while (ticks.length < maxTicks && scaleToAxis(preTick) > -0.1 * max) {
i think this preTick shows up unexpectedly sometimes, especially when the viewport width is slightly less wide

![image](https://github.com/fiberplane/fiberplane/assets/3201327/04a8bde9-d40b-4000-bb1c-0105e5893b53)

2023-07-22 11:26 UTC, brettimus commented on fiberplane-charts/src/Mondrian/generator/utils/attachSuggestionsToXAxis.ts
> +    firstBucketTimestamp - xAxis.minValue > 2 * interval;
you might want to adjust this interval, but this was my basic heuristic to short-circuit suggestions when there are missing data on the left and right side of the data. it seems to work for now, since `getTicks` will fallback to just using the axis min and max

2023-07-22 11:30 UTC, brettimus approved these changes
i added a simple solution to address the case when the xAxis min/max are far away from the bucket min/max. you'll probably want to review that!

also think i ran into some funkiness with the `preTick` logic, but i don't consider that a blocker.

2023-07-24 09:19 UTC, merged